export const DoctorType = [
  'Allergist',
  'Dermatologist',
  'Infectious disease doctor',
  'Ophthalmologist',
  'Obstetrician/gynecologist',
  'Cardiologist',
  'Endocrinologist',
  'Gastroenterologist',
  'Nephrologist',
  'Urologist',
  'Pulmonologist',
  'Otolaryngologist',
  'Neurologist',
  'Psychiatrist',
  'Oncologist',
  'Radiologist',
  'Rheumatologist',
  'General surgeon',
  'Orthopedic surgeon',
  'Cardiac surgeon',
  'Anesthesiologist',
];
